<a href="https://colab.research.google.com/github/bootstrap0/python-foundations/blob/main/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [ ]:
demo_array = np.arange(0,10)
demo_array

#demo_array[0:7] = 5
demo_array

demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1)
print(vec2)
print(vec1+vec2)

[20. 30. 40. 50.]
[100. 110. 120.]

ValueError: operands could not be broadcast together with shapes (4,) (3,)

In [ ]:
import numpy as np

# Write your code below
team_a_scores = np.array([80, 85, 90, 95, 100])
team_b_scores = np.array([70, 75, 80, 85, 90])

all_team_scores = np.concatenate(team_a_scores, team_b_scores)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
import numpy as np

# Write your code below
sales_data = [150, 200, 250, 300, 350]
array = np.array(sales_data)

sliced_array = np.split(array, [1,4])
sliced_array

[array([150]), array([200, 250, 300]), array([350])]

In [ ]:
vec = np.arange(2,5,1)
print(1/vec)
print(vec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]

In [ ]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]

/tmp/ipykernel_6359/3306162440.py:3: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)

In [ ]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(mat1)
print(np.min(mat1))
print(np.max(mat1))

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
-9
-1

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5

In [ ]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]

In [ ]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]

In [ ]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data.iloc[[1,2],[1]]

   calories
1       300
2       345

In [ ]:
import datetime
date = datetime.date(2022, 1, 29)
print(date)

2022-01-29

In [ ]:
import numpy as np
ls = [1,10,21,35,72]
type(ls)
#np.array(ls)

list

In [ ]:
list1 = [9, 8, 7, 6, 5, 4, 3, 2, 1]
np.array([list1])

array([[9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [ ]:
np.arange(start=1, stop=10, step=1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array_1 = np.linspace(0,20,6)
array_1

array([ 0.,  4.,  8., 12., 16., 20.])

In [ ]:
array_2 = np.arange(0,20,6)
array_2

array([ 0,  6, 12, 18])

In [ ]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
mat.mean()

np.float64(131.66666666666666)

In [ ]:
a = np.arange(0,20)
a[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
np.cos([0, 1, 2, 3, 4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
new_list

[1, 2, 3, 4, 5, 6]

In [ ]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
new_array

array([5, 7, 9])

In [ ]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1]=5
mat

array([[1, 2, 1],
       [5, 5, 5],
       [1, 8, 9]])

In [ ]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[0:3]=5
mat

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[2]=5
mat

array([[1, 2, 1],
       [4, 5, 9],
       [5, 5, 5]])

In [ ]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21

In [ ]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
n1 @ n2

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [ ]:
import pandas as pd
import os
from google.colab import drive
drive.flush_and_unmount()
drive.mount('/content/drive')

os.getcwd()

Drive not mounted, so nothing to flush and unmount.

MessageError: Error: credential propagation was unsuccessful

In [ ]:
os.listdir('drive/MyDrive')

['Colab Notebooks',
 'PG-AIML',
 'visa_docs.zip',
 'ceebros 6f rent agreement.doc',
 'ceebros 6f rent agreement.gdoc',
 'Umesh-PAN.pdf',
 'Umesh-Passport.pdf',
 'citi-id-card.pdf',
 'Umesh-DegreeTranscripts.pdf',
 'Umesh-Degree-EquivalencyEvaluation.pdf',
 'DeathCertificate.pdf',
 'Properties',
 'Classroom',
 'Umesh-Aadhaar.pdf',
 '1011121309.zip',
 'umesh_reddy_175550_13-04-2022_20220413081232.pdf',
 '20230422181831.pdf',
 'Untitled spreadsheet.gsheet',
 'LIFT Construction Contract for Insurance Work - 3801 High Road, Reddy.pdf',
 '5500 Rosena Trl.gsheet',
 'Verification of Insurance.pdf',
 'image.jpg',
 'IMG_1451.jpeg',
 'Team Snack Sponsors.gsheet',
 'Smoky mountains trip expenses.gsheet',
 'Saved from Chrome',
 'Houston.gsheet',
 '3.PGP-AIML-BA-UTA-Mar26.xlsx - Learning Schedule.pdf',
 'Copy of Secret Mission.gdoc']

In [ ]:
books = pd.read_csv('drive/MyDrive/PG-AIML/Python Course/books.csv')

In [ ]:
books.shape

(5000, 10)

In [ ]:
books.describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,year
count,5000.000000,5.000000e+03,4967.000000,5.000000e+03,5000.000000,5000.000000
mean,3.931932,9.752758e+12,341.094021,2.017549e+04,592.688600,2000.131800
std,0.348741,5.129254e+11,230.986115,1.175026e+05,2539.539004,8.069043
min,0.000000,8.987060e+09,1.000000,0.000000e+00,0.000000,1913.000000
25%,3.770000,9.780345e+12,200.000000,1.050000e+02,9.000000,1998.000000
50%,3.960000,9.780571e+12,304.000000,7.915000e+02,49.000000,2003.000000
75%,4.140000,9.780871e+12,416.500000,5.348750e+03,249.000000,2005.000000
max,5.000000,9.789879e+12,3342.000000,2.457092e+06,55843.000000,2019.000000

In [ ]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               5000 non-null   object
 1   author              5000 non-null   object
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64
 4   language_code       4923 non-null   object
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64
 7   text_reviews_count  5000 non-null   int64
 8   publisher           5000 non-null   object
 9   year                5000 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB

In [ ]:
books.loc[[1,4],['language_code']]

  language_code
1         en-GB
4         en-US

In [ ]:
books[(books['average_rating']>4.5) & (books['average_rating']<10)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
13,Fire in the Minds of Men: Origins of the Revol...,James H. Billington,4.54,9780765804716,eng,677.0,96,9,Basic Books,1980
35,The Lord of the Rings: The Art of the Fellowsh...,Gary Russell,4.59,9780618212903,eng,192.0,26153,102,Houghton Mifflin Harcourt,2002
54,Collected Stories III: One Night in Brazil to ...,Isaac Bashevis Singer,4.61,9781931082631,eng,915.0,23,4,Library of America,2004
63,鋼之鍊金術師 9,Hiromu Arakawa,4.57,9789861156521,NaN,184.0,4,0,東立,2004
83,Collected Essays: Notes of a Native Son / Nobo...,James Baldwin,4.61,9781883011529,eng,869.0,1495,75,Library of America (NY),1998
...,...,...,...,...,...,...,...,...,...,...
4650,The Beatles' Story on Capitol Records Part Tw...,Bruce Spizer,4.72,9780966264920,eng,264.0,29,0,Four Ninety-Eight Productions,2010
4911,In Search of Lost Time Vol. 2: Within a Buddi...,Marcel Proust,4.57,9781841598970,eng,888.0,48,1,Everyman's Library,2001
4917,Taxation of Mineral Rents,Ross Garnaut,5.00,9780198284543,eng,350.0,1,0,Oxford University Press USA,1983
4933,Oliver Wendell Holmes in Paris: Medicine Theo...,William C. Dowling,5.00,9781584655800,eng,179.0,1,1,University Press of New England,2007
4953,Complete Guide to the Bible,Reader's Digest Association,4.58,9780762100736,eng,448.0,12,3,Readers Digest,1998

In [ ]:
books[(books['year'] == 2010)].count()

title                 15
author                15
average_rating        15
isbn13                15
language_code         15
num_pages             15
ratings_count         15
text_reviews_count    15
publisher             15
year                  15
dtype: int64

In [ ]:
books[(books['publisher'] == 'DAW') & (books['average_rating'] > 4)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
71,By the Sword (Valdemar),Mercedes Lackey,4.25,9780886774639,eng,492.0,18531,249,DAW,1991
871,Storm Rising (Valdemar: Mage Storms #2),Mercedes Lackey,4.02,9780886777128,en-US,412.0,10781,86,DAW,1996
1523,Phoenix and Ashes (Elemental Masters #3),Mercedes Lackey,4.01,9780756402723,eng,480.0,6980,229,DAW,2005
1583,To Battle the Gods (Jalav Amazon Warrior #5),Sharon Green,4.07,9780886771287,eng,446.0,87,1,DAW,1986
3726,Oathblood (Valdemar: Vows and Honor #3),Mercedes Lackey,4.06,9780886777739,en-GB,394.0,9786,103,DAW,1998
4367,Joust (Dragon Jousters #1),Mercedes Lackey,4.02,9780756401535,eng,448.0,10113,263,DAW,2004

In [ ]:
books[(books['num_pages'] > 500) & (books['year'] > 2010)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
2045,Billy Budd Sailor and Other Uncompleted Writi...,Herman Melville,3.11,9780810111141,eng,1016.0,0,0,Northwestern Univ Press,2017
2775,Rick Steves' Europe Through the Back Door,Rick Steves,4.24,9781566918084,eng,808.0,3569,70,Avalon Travel,2017
3075,The Iliad,Homer,3.86,9781904633389,eng,542.0,64,8,Collector's Library,2011
3157,George Washington's Sacred Fire,Peter A. Lillback,4.18,9780978605261,eng,1200.0,694,63,Providence Forum Press,2011
3546,The Will to Power,Friedrich Nietzsche,4.05,9780394704371,eng,575.0,7931,132,Vintage Books,2011

In [ ]:
books[books['language_code'] == 'eng']['average_rating'].mean()
# use group by ??

np.float64(3.931142857142857)

In [ ]:
books[(books['language_code'] == 'spa') & (books['year']>2000)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
21,Los funerales de la Mamá Grande,Gabriel García Márquez,3.78,9780307350329,spa,160.0,4694,133,Plaza y Janes,2006
53,La Emperatriz tras el velo (Trilogía Taj Mahal...,Indu Sundaresan,4.04,9788425337604,spa,382.0,2,1,Grijalbo Mondadori Sa,2003
69,La casa de los espíritus,Isabel Allende,4.23,9780060951306,spa,454.0,608,38,HarperCollins Espanol,2001
93,Ya Sé Que Te Quiero,Billy Crystal,4.19,9780060845988,spa,40.0,0,0,Rayo,2006
107,Secretos De Familia,Julia Glass,3.57,9788496525030,spa,528.0,0,1,Puzzle-Roca,2006
...,...,...,...,...,...,...,...,...,...,...
4804,Muerte Blanca,Clive Cussler,3.91,9780307343260,spa,421.0,2,0,Debolsillo,2005
4832,Entrevista con el vampiro (Crónicas vampíricas...,Anne Rice,3.99,9788466616201,spa,463.0,1307,93,Ediciones B,2005
4890,Isabel: Princesa De Castilla España 1466,Carolyn Meyer,3.71,9788478886746,spa,184.0,8,0,Salamandra,2001
4907,Ve perro ¡Ve!,P.D. Eastman,4.09,9780375823619,spa,24.0,33,2,Random House Para Ninos,2003
4951,El librero de Kabul,Åsne Seierstad,3.76,9789706519245,spa,285.0,112,18,Grupo Océano,2004

In [ ]:
books[(books['author'] == 'Agatha Christie')].count()

title                 21
author                21
average_rating        21
isbn13                21
language_code         21
num_pages             19
ratings_count         21
text_reviews_count    21
publisher             21
year                  21
dtype: int64

In [ ]:
books.iloc[0:5,0:4]

,title,author,average_rating,isbn13
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222
2,Breach of Promise,James Scott Bell,4.00,9780310243878
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066

In [ ]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

np.int64(5)

In [ ]:
data_customer = pd.DataFrame({'customer': [101, 102, 103, 104]
                           ,'category': ['cat2', 'cat2', 'cat1', 'cat3']
                              ,'sales': [123,52, 214, 663]})

data_customer['category'].value_counts()

category
cat2    2
cat1    1
cat3    1
Name: count, dtype: int64

In [ ]:
data_customer.sort_values(by='sales', ascending=False)

   customer category  sales
3       104     cat3    663
2       103     cat1    214
0       101     cat2    123
1       102     cat2     52

In [ ]:
data_customer.loc[[1,2],['customer','sales']]
#data_customer.loc[1:3,['customer','sales']]

   customer  sales
1       102     52
2       103    214

In [ ]:
data_cust = pd.DataFrame({'customer': [101, 102, 103, 104, 101, 103]
                           ,'category': ['cat2', 'cat2', 'cat1', 'cat3', 'cat2', 'cat1']
                              ,'sales': [123,52, 214, 663, 204, 453]})
data_cust.groupby(['customer'])['sales'].mean()
#data_cust.groupby(['sales'])['customer'].mean()

customer
101    163.5
102     52.0
103    333.5
104    663.0
Name: sales, dtype: float64

In [ ]:
print(data_cust)
data_cust.drop('category', axis=1)

   customer category  sales
0       101     cat2    123
1       102     cat2     52
2       103     cat1    214
3       104     cat3    663
4       101     cat2    204
5       103     cat1    453

   customer  sales
0       101    123
1       102     52
2       103    214
3       104    663
4       101    204
5       103    453